---
title: "git_00"
author: "Estefania Maldonado"
date: "2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
An ant on the tablecloth,   
Ran into a dormant moth,  
Of many times his size.  
He showed not the least surprise.  
His business wasn't with such.  
    
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might. 
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
There are corpses,  
clammy slabs for feet,  
there is death in the bones,  
like a pure sound,  
a bark without its dog,  
out of certain bells, certain tombs,  
swelling in this humidity like lament or rain.  

I see, when alone at times,  
coffins under sail,  
setting out with the pale dead, women in their dead braids,  
bakers as white as angels,  
thoughtful girls married to notaries,  
coffins ascending the vertical river of the dead,  
  
